spring:
  profiles:
    active: prod

server:
  port: 8080

myconfig:
  welcome:
    message: Hello,
    img: hello.img
msg:
  title: Spring Boot Title

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:ishop
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      enable_lazy_load_no_trans: true
  flyway:
    locations: classpath:db/migration/h2

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${URL}
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/postgres

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${URL}
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    connectionTimeout: 300000 #( example wait connection 5 mins  )
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
      data-source-properties:
        autoReconnect: true
        oracle:
          jdbc:
            timezoneAsRegion: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/oracle